### ISSUE TITLE
auction bidders value is always equal to 0

### ISSUE THREAD

**Issue by wolfthewizard** [sqoshi/ynvest-tube-server#3]
it does not update when a player or two join the auction

**Comment by sqoshi** [comment]
After two bids with one UserId:
![image](https://user-images.githubusercontent.com/43937286/120718484-a58ec580-c4c9-11eb-8b6c-4908e2133dcf.png)

After previous two bids with one UserId + one bid with other UserId:
![image](https://user-images.githubusercontent.com/43937286/120718605-d7079100-c4c9-11eb-8215-8fb6d5ee689a.png)

**Comment by wolfthewizard** [comment]
the issue was on the client side (incorrect key name)
