### ISSUE TITLE
add debug endpoint to add ended rentals to user

### ISSUE THREAD

**Issue by wolfthewizard** [sqoshi/ynvest-tube-server#4]
it's easy to check ui behavior for current rentals by winning auctions
however rentals can take few days to finish, so we need a way to add few ended rentals to chosen user

there are alternative ways, such as to insert few 1h-long rentals into auction list

**Comment by sqoshi** [comment]
endpoint:
'rents/insert-expired-rent'

requirements:

`UserId` in request body,
video in vides table

**Comment by wolfthewizard** [comment]
does not work (throws an exception)

**Comment by sqoshi** [comment]
![image](https://user-images.githubusercontent.com/43937286/120864946-5dd17200-c58d-11eb-8960-0066ea3ab579.png)

fixed
