### ISSUE TITLE
response after bid does not contain updated lastBet for the auction

### ISSUE THREAD

**Issue by wolfthewizard** [sqoshi/ynvest-tube-server#5]

**Comment by sqoshi** [comment]
![image](https://user-images.githubusercontent.com/43937286/120719588-d4596b80-c4ca-11eb-8af0-1d4338d81bf8.png)

Somehow single row query.update() is slower than query.first().save()

(Both contain only one element, so execution time should be almost equal)

Fixed: query update -> query.first().save()

<hr>

Reason of error:

query update or second thread is slower than request response in first thread
