### ISSUE TITLE
server does not charge user after bidding or winning auction

### ISSUE THREAD

**Issue by wolfthewizard** [sqoshi/ynvest-tube-server#6]

**Comment by sqoshi** [comment]
![image](https://user-images.githubusercontent.com/43937286/120866796-edc4eb00-c590-11eb-9d5e-fa173c326f6f.png)
![image](https://user-images.githubusercontent.com/43937286/120866900-1d73f300-c591-11eb-8bcf-12dbd9ee9c5d.png)

Fixed, incorrect order of settling/ changing last bidder of auction
